const TYPES=[['orb','Energy Orb','発光する円形オーラ'],['ring','Impact Ring','衝撃波・爆発リング'],['stripe','Speed Lines','流線・斬撃テクスチャ'],['noise','Magic Noise','炎・煙・魔法ノイズ'],['star','Star Burst','閃光・キラメキ'],['grid','Tech Grid','SF UI・ホログラム'],['caustics','Water Caustics','網目のような水面模様']];
const PALETTES=[['#00e5ff','#7c3cff','#ffffff'],['#ff4d6d','#ffb703','#fff1a8'],['#24ff72','#00a8ff','#e9fff4'],['#ff7a18','#b300ff','#140018'],['#ffffff','#9ef0ff','#003b73']];
const DEFAULTS={type:'orb',size:512,seed:12,colorA:'#00e5ff',colorB:'#7c3cff',colorC:'#ffffff',intensity:76,softness:48,noise:38,twist:28,count:12,thickness:34,alpha:92,ramp:true,checker:false,blackBg:true,animate:false};
let params={...DEFAULTS}, raf=0, showTypes=true; const $=s=>document.querySelector(s);
function icon(t){return `<span class="ico">${t}</span>`}
function render(){document.body.innerHTML=`<main class="app"><header><div><p class="eyebrow">${icon('✦')} Effect Texture Generator</p><h1>TextureCreate Studio</h1><p>ゲームエフェクト向けの発光・リング・流線・ノイズテクスチャを、パラメーター調整だけで生成できます。</p></div><div class="actions"><button data-act="save">💾 Save Preset</button><button data-act="load">Load</button><button data-act="json">JSON</button><button data-act="import">⬆ Import</button><input id="presetFile" type="file" accept="application/json"></div></header><section class="workspace"><aside class="panel"><div class="panelTitle"><h2>Parameters</h2><button data-act="reset">↻ Reset</button></div><label>Type<select data-key="type">${TYPES.map(t=>`<option value="${t[0]}" ${params.type===t[0]?'selected':''}>${t[1]}</option>`).join('')}</select></label><div class="paletteRow">${PALETTES.map((pal,i)=>`<button class="swatch" data-pal="${i}">${pal.map(c=>`<span style="background:${c}"></span>`).join('')}</button>`).join('')}</div>${['colorA','colorB','colorC'].map(k=>`<label>${k}<input type="color" data-key="${k}" value="${params[k]}"></label>`).join('')}${[['size',256,1024,128],['seed',1,999,1],['intensity',0,100,1],['softness',0,100,1],['noise',0,100,1],['twist',0,100,1],['count',3,32,1],['thickness',1,100,1],['alpha',5,100,1]].map(([k,min,max,step])=>`<label>${k}<span>${params[k]}</span><input type="range" data-key="${k}" min="${min}" max="${max}" step="${step}" value="${params[k]}"></label>`).join('')}<div class="toggles">${['ramp','checker','blackBg','animate'].map(k=>`<label><input type="checkbox" data-key="${k}" ${params[k]?'checked':''}>${k}</label>`).join('')}</div></aside><section class="preview"><div class="previewTop"><div><h2 id="typeName"></h2><p id="typeDesc"></p></div><button class="primary" data-act="png">⬇ PNG 保存</button></div><div class="canvasShell"><canvas id="canvas"></canvas></div><button class="linkButton" data-act="types">全タイプ一覧を${showTypes?'隠す':'表示'}</button><div class="typeGrid" style="display:${showTypes?'grid':'none'}">${TYPES.map(t=>`<button data-type="${t[0]}" class="${params.type===t[0]?'active':''}"><strong>${t[1]}</strong><span>${t[2]}</span></button>`).join('')}</div></section></section></main>`; bind(); updateLabels(); startDraw();}
function bind(){document.querySelectorAll('[data-key]').forEach(el=>el.addEventListener('input',e=>{const k=e.target.dataset.key; params[k]=e.target.type==='checkbox'?e.target.checked:e.target.type==='range'?Number(e.target.value):e.target.value; updateLabels(); startDraw();}));document.querySelectorAll('[data-pal]').forEach(b=>b.onclick=()=>{const p=PALETTES[b.dataset.pal];Object.assign(params,{colorA:p[0],colorB:p[1],colorC:p[2]});render();});document.querySelectorAll('[data-type]').forEach(b=>b.onclick=()=>{params.type=b.dataset.type;render();});document.querySelectorAll('[data-act]').forEach(b=>b.onclick=actions[b.dataset.act]);$('#presetFile').onchange=e=>{const f=e.target.files[0]; if(f) f.text().then(t=>{params={...DEFAULTS,...JSON.parse(t)};render();});};}
const actions={save(){localStorage.setItem('texture-create-preset',JSON.stringify(params));},load(){const r=localStorage.getItem('texture-create-preset');if(r){params=JSON.parse(r);render();}},json(){download('texture-preset.json',new Blob([JSON.stringify(params,null,2)],{type:'application/json'}));},import(){$('#presetFile').click();},reset(){params={...DEFAULTS};render();},png(){const a=document.createElement('a');a.download=`texture-${params.type}-${params.seed}.png`;a.href=$('#canvas').toDataURL('image/png');a.click();},types(){showTypes=!showTypes;render();}};
function download(name,blob){const a=document.createElement('a');a.download=name;a.href=URL.createObjectURL(blob);a.click();}
function updateLabels(){const t=TYPES.find(x=>x[0]===params.type); const n=$('#typeName'), d=$('#typeDesc'); if(n){n.textContent=t[1];d.textContent=`${t[2]} / ${params.size} × ${params.size}px`;}}
function rnd(seed){return()=>{let t=seed+=0x6D2B79F5;t=Math.imul(t^t>>>15,t|1);t^=t+Math.imul(t^t>>>7,t|61);return ((t^t>>>14)>>>0)/4294967296;};}
function startDraw(){cancelAnimationFrame(raf); const loop=t=>{draw($('#canvas'),params,params.animate?t/16:0); if(params.animate) raf=requestAnimationFrame(loop);}; loop(0);}
function grad(ctx,p,x,y,r){const g=ctx.createRadialGradient(x,y,0,x,y,r);g.addColorStop(0,p.colorC);g.addColorStop(Math.max(.05,p.softness/140),p.colorA);g.addColorStop(1,p.ramp?p.colorB+'00':'transparent');return g;}
function checker(ctx,w,h){for(let y=0;y<h;y+=32)for(let x=0;x<w;x+=32){ctx.fillStyle=((x+y)/32)%2?'#ffffff14':'#ffffff08';ctx.fillRect(x,y,32,32);}}
function draw(c,p,f){const ctx=c.getContext('2d'),d=Math.min(devicePixelRatio||1,2),w=p.size,h=p.size,cx=w/2,cy=h/2,R=rnd(+p.seed+Math.floor(f*7));c.width=w*d;c.height=h*d;c.style.width=w+'px';c.style.height=h+'px';ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);if(p.blackBg){ctx.fillStyle='#05060b';ctx.fillRect(0,0,w,h);}if(p.checker)checker(ctx,w,h);ctx.globalAlpha=p.alpha/100;ctx.globalCompositeOperation='lighter';({orb,ring,stripe,noise,star,grid,caustics}[p.type])(ctx,p,cx,cy,w,h,R,f);ctx.globalAlpha=1;ctx.globalCompositeOperation='source-over';}
function orb(ctx,p,cx,cy,w,h,R,f){ctx.fillStyle=grad(ctx,p,cx,cy,w*.45);ctx.beginPath();ctx.arc(cx,cy,w*.42,0,7);ctx.fill();for(let i=0;i<p.count*8;i++){let a=R()*7+f*.03,r=R()*w*.38;ctx.fillStyle=i%3?p.colorA:p.colorC;ctx.globalAlpha=(p.alpha/100)*R()*.22;ctx.beginPath();ctx.arc(cx+Math.cos(a)*r,cy+Math.sin(a)*r,1+R()*p.noise/5,0,7);ctx.fill();}}
function ring(ctx,p,cx,cy,w,h,R,f){for(let i=0;i<5;i++){ctx.strokeStyle=i%2?p.colorA:p.colorB;ctx.lineWidth=(p.thickness/5)*(1+i*.28);ctx.globalAlpha=(p.alpha/100)*(1-i*.15);ctx.beginPath();ctx.arc(cx,cy,w*(.18+i*.055+Math.sin(f*.04+i)*.01),0,7);ctx.stroke();}star(ctx,{...p,count:Math.ceil(p.count/2),thickness:p.thickness/2},cx,cy,w,h,R,f);}
function stripe(ctx,p,cx,cy,w,h,R,f){ctx.lineCap='round';for(let i=0;i<p.count*5;i++){let y=i/(p.count*5)*h+Math.sin(i+f*.05)*p.twist,g=ctx.createLinearGradient(0,y,w,y-p.twist*2);g.addColorStop(0,'transparent');g.addColorStop(.45,p.colorA);g.addColorStop(1,p.colorC);ctx.strokeStyle=g;ctx.lineWidth=1+R()*p.thickness/2;ctx.beginPath();ctx.moveTo(-40,y);ctx.bezierCurveTo(w*.3,y-p.twist,w*.6,y+p.twist,w+40,y-p.twist*2);ctx.stroke();}}
function noise(ctx,p,cx,cy,w,h,R,f){for(let i=0;i<p.count*70;i++){let x=R()*w,y=R()*h,r=R()*R()*p.noise*2+4;ctx.fillStyle=grad(ctx,p,x,y,r);ctx.beginPath();ctx.ellipse(x+Math.sin(y+f)*p.twist*.2,y,r,r*(.35+R()),R()*7,0,7);ctx.fill();}}
function star(ctx,p,cx,cy,w,h,R,f){for(let i=0;i<p.count;i++){let a=i/p.count*7+f*.01,len=w*(.18+R()*.36),g=ctx.createLinearGradient(cx,cy,cx+Math.cos(a)*len,cy+Math.sin(a)*len);g.addColorStop(0,p.colorC);g.addColorStop(.45,p.colorA);g.addColorStop(1,'transparent');ctx.strokeStyle=g;ctx.lineWidth=1+p.thickness/4*R();ctx.beginPath();ctx.moveTo(cx,cy);ctx.lineTo(cx+Math.cos(a)*len,cy+Math.sin(a)*len);ctx.stroke();}ctx.fillStyle=grad(ctx,p,cx,cy,w*.22);ctx.beginPath();ctx.arc(cx,cy,w*.18,0,7);ctx.fill();}
function grid(ctx,p,cx,cy,w,h,R,f){ctx.strokeStyle=p.colorA;ctx.lineWidth=Math.max(1,p.thickness/20);let step=Math.max(16,90-p.count*4);for(let x=-w;x<w*2;x+=step){ctx.globalAlpha=.28;ctx.beginPath();ctx.moveTo(x+Math.sin(f*.02)*20,0);ctx.lineTo(x-w*.35,h);ctx.stroke();}for(let y=0;y<h;y+=step){ctx.globalAlpha=.18;ctx.beginPath();ctx.moveTo(0,y);ctx.lineTo(w,y+Math.sin(y+f)*p.twist);ctx.stroke();}ctx.globalAlpha=.8;ring(ctx,{...p,count:4,thickness:p.thickness/2},w/2,h/2,w,h,R,f);}
render();

function caustics(ctx,p,cx,cy,w,h,R,f){const pointCount=Math.max(10,p.count*3),points=[];for(let i=0;i<pointCount;i++){points.push({x:R()*w,y:R()*h,weight:.75+R()*.7});}const img=ctx.createImageData(w,h),data=img.data,edgeWidth=Math.max(4,p.thickness*.42),contrast=.85+p.intensity/90;for(let y=0;y<h;y++){for(let x=0;x<w;x++){let d1=1e9,d2=1e9;for(const pt of points){let dx=x-pt.x,dy=y-pt.y;dx-=Math.round(dx/w)*w;dy-=Math.round(dy/h)*h;const d=(dx*dx+dy*dy)*pt.weight;if(d<d1){d2=d1;d1=d;}else if(d<d2){d2=d;}}const gap=Math.sqrt(d2)-Math.sqrt(d1),center=Math.sqrt(d1)/(w/Math.sqrt(pointCount));let edge=Math.exp(-(gap*gap)/(edgeWidth*edgeWidth));let shade=Math.max(0,1-center*.72);let ripple=.08*Math.sin((x+y)*.035+f*.03+p.seed)+.06*Math.sin((x-y)*.026-f*.02);let v=Math.max(0,Math.min(255,(edge*235*contrast+shade*55+ripple*255)-65));const i=(y*w+x)*4;data[i]=data[i+1]=data[i+2]=v;data[i+3]=255;}}ctx.globalCompositeOperation='source-over';ctx.globalAlpha=p.alpha/100;ctx.putImageData(img,0,0);ctx.globalCompositeOperation='lighter';ctx.globalAlpha=(p.alpha/100)*.35;ctx.fillStyle=grad(ctx,{...p,colorA:'#ffffff',colorB:'#ffffff',colorC:'#ffffff',softness:70},cx,cy,w*.7);ctx.fillRect(0,0,w,h);}
